# Generated by Django 4.1.5 on 2023-01-28 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalFile",
            fields=[
                (
                    "id_medical_file",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("firstname", models.CharField(max_length=254)),
                ("lastname", models.CharField(max_length=254)),
                ("address", models.CharField(max_length=254)),
                ("age", models.IntegerField()),
                (
                    "sexe",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male"), ("U", "Unsure")],
                        default=None,
                        max_length=1,
                    ),
                ),
                (
                    "tel",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "group_sanguin",
                    models.CharField(
                        choices=[
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                ("NSS", models.CharField(max_length=254)),
                ("profession", models.CharField(max_length=254)),
                ("motif_consultation", models.CharField(max_length=254)),
                ("establishment_name", models.CharField(max_length=254)),
                ("birthday", models.DateField()),
                ("birthday_location", models.CharField(max_length=254)),
                (
                    "situation",
                    models.CharField(
                        choices=[
                            ("celebataire", "Celebataire"),
                            ("Maried", "Maried"),
                            ("Divorced", "Divorced"),
                            ("Widower", "Widower"),
                        ],
                        default=None,
                        max_length=11,
                    ),
                ),
                ("branch", models.CharField(max_length=254)),
                (
                    "smocking",
                    models.CharField(
                        choices=[("Oui", "Oui"), ("Non", "Non")],
                        default=None,
                        max_length=3,
                    ),
                ),
                ("general_maladies", models.TextField(max_length=254)),
                ("allergic_reactions_to_drugs", models.TextField(max_length=254)),
                (
                    "id_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_medical_file",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_medical_file",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
