# Generated by Django 4.1.5 on 2023-04-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="officemanager",
            name="address",
        ),
        migrations.RemoveField(
            model_name="officemanager",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="officemanager",
            name="name",
        ),
    ]
