# Generated by Django 4.1.5 on 2023-03-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="assigned_doctor_id",
        ),
        migrations.AddField(
            model_name="doctor",
            name="patients",
            field=models.ManyToManyField(related_name="doctors", to="users.patient"),
        ),
    ]
