# Generated by Django 4.1.5 on 2023-03-14 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_rename_doctor_id_appointment_doctor_and_more"),
        ("users", "0002_remove_patient_assigned_doctor_id_doctor_patients"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consultation",
            old_name="consultationDate",
            new_name="consultation_date",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="doctor_id",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="patient_id",
        ),
        migrations.AddField(
            model_name="consultation",
            name="appointment",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="appointment.appointment",
            ),
        ),
    ]
