# Generated by Django 4.1.5 on 2023-04-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_officemanager_address_officemanager_mobile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_office_manager",
            new_name="is_manager",
        ),
    ]
