# Generated by Django 4.1.5 on 2023-03-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_patient_age_patient_sexe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="patient",
            name="sexe",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], default=None, max_length=1
            ),
        ),
    ]
