# Generated by Django 4.1.5 on 2023-04-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_is_office_manager_user_is_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="admit_date",
            field=models.DateField(auto_now=True),
        ),
    ]
