# Generated by Django 4.1.5 on 2023-04-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_doctor_admit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="address",
            field=models.CharField(blank=True, default="/", max_length=40),
        ),
        migrations.AlterField(
            model_name="officemanager",
            name="address",
            field=models.CharField(blank=True, default="/", max_length=254),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.CharField(blank=True, default="/", max_length=40),
        ),
    ]
