# Generated by Django 4.1.5 on 2023-04-21 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicalrecord",
            old_name="general_maladies",
            new_name="maladies",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="establishment_name",
        ),
    ]
