from django.urls import path
from . import views

urlpatterns = [
    path("doctor/", views.doctor, name='doctor'),
    path("patient/", views.patient, name='patient'),
    path("ESI/", views.ESI, name='ESI'),
    path("ESI/profile", views.ESI_profile, name='ESI_profile'),
    path("logout/", views.logout, name="logout"),
    path("doctor/rendez-vous", views.rdv_list, name='rdv_list'),
    path("doctor/new", views.rdv_create, name='rdv_new'),
    path('doctor/pdf_view/<int:id_ordonnance>/',
         views.ViewPDF, name="pdf_view"),
    path("doctor/rdv_annuelle", views.rdv_annuelle, name='rdv_annuelle'),
    path("ESI/rdv_annuellle", views.rdv_annuellle, name='rdv_annuellle'),
    path("doctor/rendez-vous/edit/<int:id>/)",
         views.rdv_update, name='rdv_edit'),
    path("doctor/rendez-vous/delete/<int:id>/)",
         views.rdv_delete, name='rdv_delete'),
    path("doctor/profile", views.doctor_profile, name='doctor_profile'),
    path("patient/profile", views.patient_profile, name='patient_profile'),
    path("patient_list", views.patient_list, name='patient_list'),
    path("fiche_patient", views.fiche_patient, name='fiche_patient'),
    path("doctor/fiche_patient_edit/<int:id_fiche>/",
         views.fiche_patient_edit, name='fiche_patient_edit'),
    path("doctor/fiche_patient_delete/<int:id_fiche>/",
         views.fiche_patient_delete, name='fiche_patient_delete'),
    path('doctor/fichePDF/<int:id_fiche>/', views.fichePDF, name="fichePDF"),
    path("doctor/ordonnance", views.ordonnance, name='ordonnance'),
    path("doctor/ordonnance_list", views.ordonnance_list, name='ordonnance_list'),
    path("doctor/ordonnance_edit/<int:id_ordonnance>/",
         views.ordonnance_edit, name='ordonnance_edit'),
    path("doctor/ordonnance_delete/<int:id_ordonnance>/",
         views.ordonnance_delete, name='ordonnance_delete'),
    path("doctor/consultation_list",
         views.consultation_list, name='consultation_list'),
    path("doctor/consultation_list_patient",
         views.consultation_list_patient, name='consultation_list_patient'),
    path("doctor/consultation", views.consultation, name='consultation'),
    path("doctor/consultation_edit/<int:id_consultation>/",
         views.consultation_edit, name='consultation_edit'),
    path("doctor/consultation_delete/<int:id_consultation>/",
         views.consultation_delete, name='consultation_delete'),
    path('doctor/Statistique', views.Data, name='Data'),
    path('patient/rd', views.rd, name='rd'),
    path("patient/rdv_neww", views.rd_create, name='rdv_neww'),
    path("patient/rd_edit/<int:id>/", views.rd_update, name='rd_edit'),
    path("patient/rd_delete/<int:id>/", views.rd_delete, name='rd_delete'),

]
