# Generated by Django 4.1.5 on 2023-01-31 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id_appointment", models.AutoField(primary_key=True, serialize=False)),
                ("date_appointment", models.DateTimeField()),
                ("reason_appointment", models.CharField(max_length=255)),
                ("location_appointment", models.CharField(max_length=255)),
                ("notes_appointment", models.TextField(blank=True)),
                ("is_confirmed", models.BooleanField(default=False)),
                (
                    "id_doctor",
                    models.ForeignKey(
                        default="3",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_patient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
