# Generated by Django 4.1.5 on 2023-04-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="appointment_date",
            new_name="date",
        ),
    ]
