# Generated by Django 3.2.6 on 2021-08-12 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_sante', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CabinetDentaire',
            new_name='Cabinet',
        ),
    ]
