# Generated by Django 3.2.6 on 2021-08-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_sante', '0002_rename_cabinetdentaire_cabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='observation',
            field=models.TextField(max_length=254),
        ),
    ]
