# Generated by Django 3.2.6 on 2021-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_sante', '0003_alter_ordonnance_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichepatient',
            name='sexe',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure')], max_length=1),
        ),
    ]
