# Generated by Django 4.1.5 on 2023-01-31 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medicalfile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id_prescription",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("medication", models.CharField(max_length=254)),
                ("date_prescribed", models.DateTimeField()),
                ("duration", models.IntegerField()),
                ("observation", models.TextField(max_length=254)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_medical_file",
                        to="medicalfile.medicalfile",
                    ),
                ),
            ],
        ),
    ]
