# Generated by Django 4.1.5 on 2023-01-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medicalfile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                ("id_ordonnance", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                ("medicament", models.CharField(max_length=254)),
                ("observation", models.TextField(max_length=254)),
                (
                    "name_patient",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiche_patient",
                        to="medicalfile.fichepatient",
                    ),
                ),
            ],
        ),
    ]
