# Generated by Django 4.1.5 on 2023-01-26 08:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medical_office",
            fields=[
                ("id_cabinet", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=254)),
                ("address", models.CharField(max_length=254)),
                ("email", models.EmailField(max_length=254)),
                (
                    "tel",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                (
                    "fax",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
            ],
        ),
    ]
