# Generated by Django 4.1.5 on 2023-01-31 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id_consultation",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date_consultation", models.DateTimeField()),
                ("notes", models.TextField(max_length=254)),
                ("diagnosis", models.TextField()),
                ("treatment", models.TextField()),
                (
                    "id_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cons_medecin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cons_patient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
