# Generated by Django 4.1.5 on 2023-01-26 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Facture",
            fields=[
                ("id_facture", models.AutoField(primary_key=True, serialize=False)),
                ("prix", models.FloatField()),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id_consultation",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("contenue", models.TextField(max_length=254)),
                ("antecedant", models.CharField(max_length=254)),
                ("traitement", models.CharField(max_length=254)),
                ("date_consultation", models.DateTimeField()),
                (
                    "id_facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cons_fact",
                        to="doctor.facture",
                    ),
                ),
                (
                    "id_medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cons_medecin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cons_patient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
